export const HERO_MOBILE_BLUR =
  "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAADCAYAAAC09K7GAAAACXBIWXMAABYlAAAWJQFJUiTwAAAAPklEQVR4nAEzAMz/AJOVsf55bHX/h1x6/6KJsf4AhHrB/2yFv/82GGn/bkSB/wCahKv+d2+e/1VHk/91aIT++Ykdk2ghjJoAAAAASUVORK5CYII=";
export const HERO_TABLET_BLUR =
  "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAADCAYAAAC09K7GAAAACXBIWXMAABYlAAAWJQFJUiTwAAAAPklEQVR4nAEzAMz/AI2Oqf9sXWT/flBq/5yAqf8Ah33D/3WMxv86Hmv/az9//wCUfab+bWaW/1BCkP9rXHv+5acc3+bRwtMAAAAASUVORK5CYII=";
export const HERO_DESKTOP_BLUR =
  "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAADCAYAAAC09K7GAAAACXBIWXMAABYlAAAWJQFJUiTwAAAAPklEQVR4nAEzAMz/AI6Pqv9uYGb/gFJs/52Bq/8Ah33D/3OLxf86Hmv/az9+/wCVfqf+bmeW/1FDkf9sXXz+6Nwc+em7JxUAAAAASUVORK5CYII=";
